# In this Notebook I am starting my TensorFlow journey, writing code for machine learning

In [1]:
import tensorflow as tf

print(tf.__version__)

2.14.0


In [3]:
#creating tensors using tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the num of dimensions using ndim of tensor
scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of a vector
vector.ndim

1

In [10]:
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [11]:
matrix.ndim

2

In [13]:
# Another Matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.,],
                              [8.,9.]],dtype = tf.float16)    #Specify the datatype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another_matrix.ndim

2